// Generated by https://quicktype.io
import "dart:convert";

// IcecreamData icecreamDatafromJson(String str) {
//   final jsonData = json.decode(str);
//   return IcecreamData.fromJson(jsonData);
// }
IcecreamData icecreamDatafromJson(String? str) {
  if (str == null) {
    print("JSON ERROR ********************************");
    throw ArgumentError('JSON string is null');
  }
  print(
      "icecreamDataFromJson inside function ********************************");
  final jsonData = json.decode(str);
  final List<dynamic> icecreamsJson = jsonData['icecreams'];

  List<Icecream> icecreams =
      icecreamsJson.map((json) => Icecream.fromJson(json)).toList();
  print(icecreams.toString());
  return IcecreamData(icecreams: icecreams);
}

String icecreamDataToJson(IcecreamData data) {
  final dyn = data.toJson();
  return json.encode(dyn);
}

class IcecreamData {
  List<Icecream>? icecreams;

  IcecreamData({
    this.icecreams,
  });

  factory IcecreamData.fromJson(Map<String, dynamic> json) => new IcecreamData(
        icecreams: List<Icecream>.from(
            json["icecreams"].map((x) => Icecream.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "icecreams": new List<dynamic>.from(icecreams!.map((x) => x.toJson())),
      };
}

class Icecream {
  String flavor;
  String description;
  List<String> toppings;
  double price;
  String image;
  List<Ingredient> ingredients;

  Icecream({
    required this.flavor,
    required this.description,
    required this.toppings,
    required this.price,
    required this.image,
    required this.ingredients,
  });

  factory Icecream.fromJson(Map<String, dynamic> json) => Icecream(
        flavor: json["flavor"],
        description: json["description"],
        toppings: List<String>.from(json["toppings"].map((x) => x)),
        price: json["price"].toDouble(),
        image: json["image"],
        ingredients: List<Ingredient>.from(
            json["ingredients"].map((x) => Ingredient.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "flavor": flavor,
        "description": description,
        "toppings": List<dynamic>.from(toppings.map((x) => x)),
        "price": price,
        "image": image,
        "ingredients": List<dynamic>.from(ingredients.map((x) => x.toJson())),
      };
}

class Ingredient {
  String name;
  String quantity;

  Ingredient({
    required this.name,
    required this.quantity,
  });

  factory Ingredient.fromJson(Map<String, dynamic> json) => Ingredient(
        name: json["name"],
        quantity: json["quantity"],
      );

  Map<String, dynamic> toJson() => {"name": name, "quantity": quantity};
}
