
// Map<String, dynamic> toJson()=>{

//     "icecreams": List<dynamic>.from(icecreams)
// };
// Generated by https://quicktype.io

class Icecreams {
  List<Icecream> icecreams;

  Icecreams({
    required this.icecreams,
  });
}

class Icecream {
  String flavor;
  String description;
  List<String> toppings;
  double price;
  String image;
  List<Ingredient> ingredients;

  Icecream({
   required this.flavor,
   required this.description,
   required this.toppings,
   required this.price,
   required this.image,
   required this.ingredients,
  });
}

class Ingredient {
  String name;
  String quantity;

  Ingredient({
   required this.name,
   required this.quantity,
  });
}
